/* -*- coding: utf-8 -*- マルチバイト */

// Copyright 2026 Kazuma Arino. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#include <mfg_pal/pal.hpp>
#include "mfg_resource.hpp"

#ifdef _WIN32
    #pragma warning( disable: 4065 ) // defaultのみのswitch文、未翻訳のリソースでこういうコードを生成している。
#endif

namespace mfg_resource
{

const char* UIResourceStringGen( UIResId rid, mfg_pal::NLanguage lang )
{
  switch( lang )
  {
    case mfg_pal::NL_JAPANESE:
      switch( rid ) {
        case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "簡単のため、bottomPositiveとrightPositive方向をまず計算する。";
        case UIResId::COMMENT_DIFF_THRESHOLD: return "これ以上RGBのdistanceがあればedgeとみなす";
        case UIResId::COMMENT_EDGE_LEN_ACCM: return "accmは最初のピクセルがエッジじゃなければ-1とする。\n-1はEND_FOUND_MASKも含むことに注意。\n\n通常はbottomPositiveとrightPosivieの長さ+END_FOUND_MASK";
        case UIResId::COMMENT_EDGE_LEN: return "bottomとrightのみだが、それぞれpositive方向とnegative方向があり、合計4要素。\nエッジの終わりを見つけたらEND_FOUND_MASKのビットを立てる。\n長さは7までを探し、それ以上は終わりが見つからなかった、と処理する。";
        case UIResId::COMMENT_EDGE_TENSOR: return "対象のピクセルの下と右がエッジになっているかを返す";
        case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "ガウスぼかしの幅";
        case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "luminanceをガウスぼかし、2パスで";
        case UIResId::COMMENT_NEGA_POSI_DIFF: return "一つ上のreduceとの違いはprevEndとcurEndの所だけ。\n工夫すれば一つにまとめられそうだが、DRAMアクセスの数は変わらないので速度は分けても大差無いはず。";
        case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "Negative方向ではleftは次のrightなので、一つ遡って終わらせる。";
        case UIResId::COMMENT_NON_ZERO_NON_END: return "iが0でなく、まだ終わりも見つかっていない";
        case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "rgbからxyzカラーにして、bloomを足して戻す";
        case UIResId::COMMENT_U8V4_OPTIMIZE: return "u8v4の最適化を期待してu8v4で返す";
        case UIResId::LABEL_BLEND_ALPHA: return "重ね合わせるアルファ";
        case UIResId::LABEL_BLUR_WIDTH: return "ぼかし幅";
        case UIResId::LABEL_CENTER: return "中心";
        case UIResId::LABEL_CONTROL_POINT: return "制御点";
        case UIResId::LABEL_DELTA_REGION_TOP: return "ずらす領域のトップ";
        case UIResId::LABEL_DELTA_REGION: return "すらす領域の範囲";
        case UIResId::LABEL_DELTA_SIZE: return "ずらす度合い";
        case UIResId::LABEL_DENSITY: return "密度";
        case UIResId::LABEL_DISTORT: return "歪み";
        case UIResId::LABEL_GRID_SIZE: return "グリッドサイズ";
        case UIResId::LABEL_LENGTH_RANDOMNESS: return "長さのランダムさ";
        case UIResId::LABEL_LENGTH: return "長さ";
        case UIResId::LABEL_MIRROR_POS: return "鏡の位置";
        case UIResId::LABEL_NOISE_STRENGTH: return "ノイズ強さ";
        case UIResId::LABEL_PEPPER_THRESHOLD: return "ごましきい値";
        case UIResId::LABEL_POINT_LOWER_RIGHT: return "右下の点";
        case UIResId::LABEL_RADIUS: return "半径";
        case UIResId::LABEL_RANDOM_STRENGTH: return "ランダムの強さ";
        case UIResId::LABEL_SALT_THRESHOLD: return "塩しきい値";
        case UIResId::LABEL_SIZE: return "サイズ";
        case UIResId::LABEL_STRENGTH: return "強さ";
        case UIResId::LABEL_THRESHOLD: return "しきい値";
        case UIResId::LABEL_WIDTH_RANDOMNESS: return "幅のランダムさ";
        case UIResId::LABEL_WIDTH: return "幅";
        case UIResId::TITLE_BEZIER: return "ベジエ";
        case UIResId::TITLE_BLOOM: return "ブルームフィルタ";
        case UIResId::TITLE_CRYSTALLIZE: return "クリスタライズフィルタ";
        case UIResId::TITLE_DRAG: return "引っ張るフィルタ";
        case UIResId::TITLE_FISHEYE: return "魚眼";
        case UIResId::TITLE_GRAIN: return "Grainフィルタ";
        case UIResId::TITLE_LENS_BLUR: return "レンズぼかし";
        case UIResId::TITLE_LINE_CONCENT: return "集中線";
        case UIResId::TITLE_LINE_PARALLEL: return "流線";
        case UIResId::TITLE_MAGNIFIER: return "虫眼鏡";
        case UIResId::TITLE_MLAA: return "アンチエイリアス(MLAA)";
        case UIResId::TITLE_MOSAIC: return "モザイク";
        case UIResId::TITLE_MOTION_BLUR: return "移動ぼかし";
        case UIResId::TITLE_NEGAPOSI: return "ネガポジ反転フィルター";
        case UIResId::TITLE_NIGHTVISION: return "暗視スコープ";
        case UIResId::TITLE_PERLIN: return "パーリンノイズ";
        case UIResId::TITLE_REGION_DELTA: return "領域ずらし";
        case UIResId::TITLE_REPEAT: return "繰り返し";
        case UIResId::TITLE_RG_DELTA: return "RGずらし";
        case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "ごま塩ノイズ";
        case UIResId::TITLE_SAND_STORM: return "砂嵐";
        case UIResId::TITLE_SPHERE_PROJECTION: return "球面射影";
        case UIResId::TITLE_WATER_MIRROR: return "水鏡";
        case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "ノイズ除去（重み付きメディアンフィルター）";
        case UIResId::TITLE_WINDING: return "うねうね";
        case UIResId::TITLE_ZIGZAG: return "ジグザグ";
        case UIResId::LABEL_LIGHT_SOURCE_POS: return "光源位置";
        case UIResId::LABEL_GHOST_INTERVAL: return "ゴースト間隔";
        case UIResId::LABEL_GHOST_INIT_POS: return "ゴーストの初期位置";
        case UIResId::LABEL_COUNT_NUM: return "カウント数";
        case UIResId::TITLE_LENS_FLARE: return "レンズフレア";
        case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "ダウンサンプルしたサイズ";
        case UIResId::TITLE_POINT_LIGHT: return "点光源";
        case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "点光源+レンズフレア";
        case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "光源強度";
        case UIResId::LABEL_GHOST_STRENGTH: return "ゴースト強度";
        case UIResId::LABEL_AMPLITUDE: return "振幅";
        case UIResId::LABEL_PERIOD: return "周期";
        case UIResId::LABEL_INTERVAL: return "間隔";
        case UIResId::TITLE_COPPER_ENGRAVE: return "銅版画トーン";
        case UIResId::LABEL_BRIGHTNESS: return "明るさ";
        case UIResId::LABEL_ROUGHNESS: return "粗さ";
        case UIResId::TITLE_CRT_FILTER: return "CRTフィルター";
        default: break;
      }
    case mfg_pal::NL_CHINESE_SIMP:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    case mfg_pal::NL_CHINESE_TRAD:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    case mfg_pal::NL_KOREAN:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    case mfg_pal::NL_PORTUGUESE:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    case mfg_pal::NL_SPANISH:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    case mfg_pal::NL_GERMAN:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    case mfg_pal::NL_FRENCH:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    case mfg_pal::NL_RUSSIAN:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    case mfg_pal::NL_HINDI:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    case mfg_pal::NL_BENGALI:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    case mfg_pal::NL_POLISH:
      switch( rid ) {
        // case UIResId::LABEL_MIRROR_POS: return "";
        // case UIResId::LABEL_RADIUS: return "";
        // case UIResId::LABEL_SIZE: return "";
        // case UIResId::LABEL_STRENGTH: return "";
        // case UIResId::LABEL_SALT_THRESHOLD: return "";
        // case UIResId::LABEL_PEPPER_THRESHOLD: return "";
        // case UIResId::TITLE_LENS_BLUR: return "";
        // case UIResId::TITLE_MOSAIC: return "";
        // case UIResId::TITLE_MOTION_BLUR: return "";
        // case UIResId::TITLE_NEGAPOSI: return "";
        // case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "";
        // case UIResId::TITLE_SAND_STORM: return "";
        // case UIResId::TITLE_WATER_MIRROR: return "";
        // case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "";
        // case UIResId::TITLE_CRYSTALLIZE: return "";
        // case UIResId::TITLE_MAGNIFIER: return "";
        // case UIResId::TITLE_BLOOM: return "";
        // case UIResId::TITLE_FISHEYE: return "";
        // case UIResId::TITLE_SPHERE_PROJECTION: return "";
        // case UIResId::TITLE_ZIGZAG: return "";
        // case UIResId::TITLE_PERLIN: return "";
        // case UIResId::TITLE_NIGHTVISION: return "";
        // case UIResId::TITLE_GRAIN: return "";
        // case UIResId::TITLE_RG_DELTA: return "";
        // case UIResId::TITLE_REGION_DELTA: return "";
        // case UIResId::TITLE_REPEAT: return "";
        // case UIResId::LABEL_GRID_SIZE: return "";
        // case UIResId::LABEL_RANDOM_STRENGTH: return "";
        // case UIResId::LABEL_CENTER: return "";
        // case UIResId::LABEL_DISTORT: return "";
        // case UIResId::LABEL_THRESHOLD: return "";
        // case UIResId::LABEL_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "";
        // case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "";
        // case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "";
        // case UIResId::LABEL_NOISE_STRENGTH: return "";
        // case UIResId::LABEL_DELTA_REGION_TOP: return "";
        // case UIResId::LABEL_DELTA_REGION: return "";
        // case UIResId::LABEL_DELTA_SIZE: return "";
        // case UIResId::LABEL_BLEND_ALPHA: return "";
        // case UIResId::LABEL_POINT_LOWER_RIGHT: return "";
        // case UIResId::TITLE_MLAA: return "";
        // case UIResId::COMMENT_DIFF_THRESHOLD: return "";
        // case UIResId::COMMENT_EDGE_TENSOR: return "";
        // case UIResId::COMMENT_U8V4_OPTIMIZE: return "";
        // case UIResId::COMMENT_EDGE_LEN: return "";
        // case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "";
        // case UIResId::COMMENT_EDGE_LEN_ACCM: return "";
        // case UIResId::COMMENT_NON_ZERO_NON_END: return "";
        // case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "";
        // case UIResId::COMMENT_NEGA_POSI_DIFF: return "";
        // case UIResId::TITLE_DRAG: return "";
        // case UIResId::TITLE_WINDING: return "";
        // case UIResId::TITLE_LINE_CONCENT: return "";
        // case UIResId::TITLE_LINE_PARALLEL: return "";
        // case UIResId::TITLE_BEZIER: return "";
        // case UIResId::LABEL_WIDTH: return "";
        // case UIResId::LABEL_WIDTH_RANDOMNESS: return "";
        // case UIResId::LABEL_DENSITY: return "";
        // case UIResId::LABEL_LENGTH: return "";
        // case UIResId::LABEL_LENGTH_RANDOMNESS: return "";
        // case UIResId::LABEL_CONTROL_POINT: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_POS: return "";
        // case UIResId::LABEL_GHOST_INTERVAL: return "";
        // case UIResId::LABEL_GHOST_INIT_POS: return "";
        // case UIResId::LABEL_COUNT_NUM: return "";
        // case UIResId::TITLE_LENS_FLARE: return "";
        // case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "";
        // case UIResId::TITLE_POINT_LIGHT: return "";
        // case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "";
        // case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "";
        // case UIResId::LABEL_GHOST_STRENGTH: return "";
        // case UIResId::LABEL_AMPLITUDE: return "";
        // case UIResId::LABEL_PERIOD: return "";
        // case UIResId::LABEL_INTERVAL: return "";
        // case UIResId::TITLE_COPPER_ENGRAVE: return "";
        // case UIResId::LABEL_BRIGHTNESS: return "";
        // case UIResId::LABEL_ROUGHNESS: return "";
        // case UIResId::TITLE_CRT_FILTER: return "";
        default: break;
      }
    // 英語や存在しない翻訳はswitchの外でまとめて英語として処理
    default: break;      
  }
  // 英語か翻訳が存在しない。
  // 英語を返す
  // case mfg_pal::NL_ENGLISH:
  switch( rid ) {
    case UIResId::COMMENT_BOTTOM_RIGHT_POS: return "For simplicity, we first calculate the bottomPositive and rightPositive directions only.";
    case UIResId::COMMENT_DIFF_THRESHOLD: return "If RGB distance is bigger than this value, it's considered an edge";
    case UIResId::COMMENT_EDGE_LEN_ACCM: return "accm:\nIf first pixel is not edge, -1.\nNote -1 also include END_FOUND_MASK.\n\nElse length of bottomPositive or rightPositive + END_FOUND_MASK.";
    case UIResId::COMMENT_EDGE_LEN: return "Bottom and right, positive and negative for each, total 4 elements.\nIf you find end of edge, turn on END_FOUND_MASK bit.\nMax length is 7 and treat 'end not found' if longer than 7.";
    case UIResId::COMMENT_EDGE_TENSOR: return "Return whether bottom or right of target pixel is edge or not.";
    case UIResId::COMMENT_GAUSS_BLUR_WIDTH: return "Size of Gaus Blur";
    case UIResId::COMMENT_LUMINANCE_GAUSS_BLUR_TWO_PASS: return "Gaus blur luminance, 2 pass.";
    case UIResId::COMMENT_NEGA_POSI_DIFF: return "The only difference from the above reduce is in `prevEnd` and `curEnd`.\nWhile it might be possible to combine them with some refactoring, the number of DRAM accesses won't change.\nThere should be little difference in speed even if kept separate.";
    case UIResId::COMMENT_NEGATIVE_LEFT_HANDLING: return "For negative direction, left is the right of next pixel. So we finish at previous iteration.";
    case UIResId::COMMENT_NON_ZERO_NON_END: return "i is not 0 and edge end is not yet found.";
    case UIResId::COMMENT_RGB_XYZ_BLOOM_ADD: return "Convert from RGB to xyz, add to bloom, then convert back.";
    case UIResId::COMMENT_U8V4_OPTIMIZE: return "Return as u8v4 for u8v4 special optimization.";
    case UIResId::LABEL_BLEND_ALPHA: return "Blending Alpha";
    case UIResId::LABEL_BLUR_WIDTH: return "Blur Width";
    case UIResId::LABEL_CENTER: return "Center";
    case UIResId::LABEL_CONTROL_POINT: return "Control Point";
    case UIResId::LABEL_DELTA_REGION_TOP: return "Top of Delta Region";
    case UIResId::LABEL_DELTA_REGION: return "Area of Delta Region";
    case UIResId::LABEL_DELTA_SIZE: return "Delta";
    case UIResId::LABEL_DENSITY: return "Density";
    case UIResId::LABEL_DISTORT: return "Distort";
    case UIResId::LABEL_GRID_SIZE: return "Grid Size";
    case UIResId::LABEL_LENGTH_RANDOMNESS: return "Length Randomness";
    case UIResId::LABEL_LENGTH: return "Length";
    case UIResId::LABEL_MIRROR_POS: return "Mirror Position";
    case UIResId::LABEL_NOISE_STRENGTH: return "Noise Strength";
    case UIResId::LABEL_PEPPER_THRESHOLD: return "Pepper Threshold";
    case UIResId::LABEL_POINT_LOWER_RIGHT: return "Right Bottom Corner";
    case UIResId::LABEL_RADIUS: return "Radius";
    case UIResId::LABEL_RANDOM_STRENGTH: return "Random Strength";
    case UIResId::LABEL_SALT_THRESHOLD: return "Salt Threshold";
    case UIResId::LABEL_SIZE: return "Size";
    case UIResId::LABEL_STRENGTH: return "Strength";
    case UIResId::LABEL_THRESHOLD: return "Threshold";
    case UIResId::LABEL_WIDTH_RANDOMNESS: return "Width Randomness";
    case UIResId::LABEL_WIDTH: return "Width";
    case UIResId::TITLE_BEZIER: return "Bezier";
    case UIResId::TITLE_BLOOM: return "Bloom Filter";
    case UIResId::TITLE_CRYSTALLIZE: return "Crystallize Filter";
    case UIResId::TITLE_DRAG: return "Drag Filter";
    case UIResId::TITLE_FISHEYE: return "Fisheye Lens";
    case UIResId::TITLE_GRAIN: return "Grain Filter";
    case UIResId::TITLE_LENS_BLUR: return "Lens Blur";
    case UIResId::TITLE_LINE_CONCENT: return "Line Concent";
    case UIResId::TITLE_LINE_PARALLEL: return "Line Parallel";
    case UIResId::TITLE_MAGNIFIER: return "Magnifier";
    case UIResId::TITLE_MLAA: return "Antialias(MLAA)";
    case UIResId::TITLE_MOSAIC: return "Mosaic";
    case UIResId::TITLE_MOTION_BLUR: return "Motion Blur";
    case UIResId::TITLE_NEGAPOSI: return "Negaposi filter";
    case UIResId::TITLE_NIGHTVISION: return "Night Vision";
    case UIResId::TITLE_PERLIN: return "Perlin Noise";
    case UIResId::TITLE_REGION_DELTA: return "Region Delta";
    case UIResId::TITLE_REPEAT: return "Repeat";
    case UIResId::TITLE_RG_DELTA: return "RG Delta";
    case UIResId::TITLE_SALT_AND_PEPPER_NOISE: return "Salt and Pepper Noise";
    case UIResId::TITLE_SAND_STORM: return "Sand Storm";
    case UIResId::TITLE_SPHERE_PROJECTION: return "Sphere Projection";
    case UIResId::TITLE_WATER_MIRROR: return "Water Mirror";
    case UIResId::TITLE_WEIGHTED_MEDIAN_FILTER: return "Denoise(Weighted Median Filter)";
    case UIResId::TITLE_WINDING: return "Winding Filter";
    case UIResId::TITLE_ZIGZAG: return "Zigzag";
    case UIResId::LABEL_LIGHT_SOURCE_POS: return "Light Source Pos";
    case UIResId::LABEL_GHOST_INTERVAL: return "Ghost Interval";
    case UIResId::LABEL_GHOST_INIT_POS: return "Ghost Initial Pos";
    case UIResId::LABEL_COUNT_NUM: return "Count";
    case UIResId::TITLE_LENS_FLARE: return "Lens Flare";
    case UIResId::COMMENT_DOWNSAMPLE_SIZE: return "Size for downsample.";
    case UIResId::TITLE_POINT_LIGHT: return "Point Light";
    case UIResId::TITLE_POINT_LIGHT_AND_LENS_FLARE: return "Point Light and Lens Flare";
    case UIResId::LABEL_LIGHT_SOURCE_INTENSITY: return "Light Source Intensity";
    case UIResId::LABEL_GHOST_STRENGTH: return "Ghost Strength";
    case UIResId::LABEL_AMPLITUDE: return "Amplitude";
    case UIResId::LABEL_PERIOD: return "Period";
    case UIResId::LABEL_INTERVAL: return "Interval";
    case UIResId::TITLE_COPPER_ENGRAVE: return "Copper Engrave Tone";
    case UIResId::LABEL_BRIGHTNESS: return "Brightness";
    case UIResId::LABEL_ROUGHNESS: return "Roughness";
    case UIResId::TITLE_CRT_FILTER: return "CRT Filter";
    default: return ""; // 追加漏れ。空文字列を返しておく。
  }
}

}///< mfg_resource
