from invoke import task
from os import path
import os
from glob import glob
import re
import csv


def collect_enum_ids(fpath, ecsname):
  """
  fpathにあるファイル（.hppを想定）から、enum class [escaname] {...}
  という定義を探し出し、...の間にあるenumのIDの一覧をリストで返す。
  """
  idstrs = []
  ecsBegin = False
  with open(fpath, 'r') as f:    
    for line in f:
      if ecsBegin:
        idMatch = re.search(r' *([A-Z][^,]*),.*', line)
        if idMatch:
          idstrs.append(idMatch.group(1))
        else:
          closeMatch = re.search(r' *};', line)
          if closeMatch:
            return idstrs
      else:
        match = re.search(fr'enum class *{ecsname}', line)
        if match:
          ecsBegin = True
  return idstrs


def update_trans_str_case(fpath, ecsname, funcName, idlist):
  """
  mfg_resource_trans_str.cppの言語ごとのcaseのうち、idlistにあるがエントリが無いIDを
  以下のようなC++コメントとして追加する
  // case ResId::SOME_ID: return "";
  """
  # ステートマシン
  state_init = 0
  state_func_begin = 1
  state_lang_switch = 2
  state_rid_case = 3
  state_deflang_begin = 4
  state_deflang_rid_case = 5
  state_deflang_end = 6
  state = state_init

  lines = []
  case_found = set()
  with open(fpath, 'r', encoding='utf_8_sig') as f:
    for line in f:
      if state == state_init:
        lines.append(line)
        funcMatch = re.search(f'const char\\* {funcName}', line)
        if funcMatch:
          state = state_func_begin
      elif state == state_func_begin:
        lines.append(line)
        langSwitchMatch = re.search(r' *switch\( *lang *\)', line)
        if langSwitchMatch:
          state = state_lang_switch
      elif state == state_lang_switch:        
        lines.append(line)
        ridSwitchMatch = re.search(r' *switch\( *rid *\)', line)
        if ridSwitchMatch:
          state = state_rid_case
          case_found = set()
        else:
          engMatch = re.search(r'case mfg_pal::NL_ENGLISH:', line)
          if engMatch:
            state = state_deflang_begin
      elif state == state_rid_case:
        caseMatch = re.search(f'case {ecsname}::([A-Z][^:]*)', line)
        if caseMatch:
          lines.append(line)
          case_found.add(caseMatch.group(1))
        else:
          defMatch = re.search(r'default:', line)
          if defMatch:
            # case_foundに無いidの一覧を探して、そのコメントを追加
            for id in idlist:
              if id not in case_found:
                lines.append(f'        // case {ecsname}::{id}: return "";\n')
            lines.append(line)
            state = state_lang_switch
          else:
            lines.append(line)
      elif state == state_deflang_begin:
        lines.append(line)
        ridSwitchMatch = re.search(r' *switch\( *rid *\)', line)
        if ridSwitchMatch:
          state = state_deflang_rid_case
          case_found = set()
      elif state == state_deflang_rid_case:
        caseMatch = re.search(f'case {ecsname}::([A-Z][^:]*)', line)
        if caseMatch:
          lines.append(line)
          case_found.add(caseMatch.group(1))
        else:
          defMatch = re.search(r'default:', line)
          if defMatch:
            # case_foundに無いidの一覧を探して、そのコメントを追加
            for id in idlist:
              if id not in case_found:
                lines.append(f'    // case {ecsname}::{id}: return "";\n')
            lines.append(line)
            state = state_deflang_end
          else:
            lines.append(line)
      else:
          # state == state_deflang_end
        lines.append(line)
  return "".join(lines)



@task
def test_one(c):
  ids = collect_enum_ids("../../_mfg/mfg_parser.hpp", "TokenType")
  # print(ids)
  res = gen_rev_ecs_map("TokenType", ids, "g_revTTMap")
  print(res)





cpp_header ="""/* -*- coding: utf-8 -*- マルチバイト */

/*
  This file is automatically generated by resources/tasks.py.
  Do not edit manually.
*/

#include "mfg_resource.hpp"
#include "mfg_tool.hpp"
#include "mfg_ir_util.hpp" // FmtRString、本当はir_utilにあるのがおかしいがほかにちょうど良いのが無いのでir_utilに置いてるせいでここでincludeする羽目に。
#include <map>
#include <string>

namespace mfg_resource
{

"""

cpp_resmap_gen_footer = """

ResId LookupResId( const char* resIdStr )
{
  auto res = g_resMap.find( resIdStr );
  if (res == g_resMap.end())
  {
    auto str = mfg_internal::FmtRString( ResId::UNKNOWN_RESOURCE_ID, resIdStr );
    throw mfg_internal::UserError( str );
  }
  return res->second;
}

bool ResIdExist( const char* resIdStr )
{
  return g_resMap.end() != g_resMap.find( resIdStr );
}

UIResId LookupUIResId( const char* resIdStr )
{
  auto res = g_uiResMap.find( resIdStr );
  if (res == g_uiResMap.end())
  {
    auto str = mfg_internal::FmtRString( ResId::UNKNOWN_RESOURCE_ID, resIdStr );
    throw mfg_internal::UserError( str );
  }
  return res->second;
}


"""

resourece_ns_footer = """}///< mfg_resource
"""

parser_ns_header = """
/*
  これはこのファイルに置くのは適切では無いが、mfg_parserの自動生成ファイルをわざわざ作るのも手間が多いのでここに間借り。
*/
#include "mfg_parser.hpp"
namespace mfg_parser
{

"""

cpp_revres_map_gen_footer = """

std::string TokenTypeToStr( TokenType tt )
{
  auto res = g_revTTMap.find( tt );
  if (res == g_revTTMap.end())
  {
    throw mfg_internal::InternalError( Format( "Unknown TT, never reached here: {0}", (int)(tt) ) );
  }
  return res->second;
}

"""

parser_ns_footer = """}///< mfg_parser
"""

def gen_res_map(csname, idlist, gvarName):
  """
  以下のような文字列からenum idのlookupをするmapを生成。
  static const std::map<std::string, ResId> g_resMap{
    {"OFFSET_IS_OUTSIDE_OF_SOURCE_SIZE", ResId::OFFSET_IS_OUTSIDE_OF_SOURCE_SIZE},
    ...
  };

  ここでcsnameはResIdに、gvarNameはg_resMapに対応する。
  """
  builder = []
  builder.append(f"static const std::map<std::string, {csname}> {gvarName}{{")
  for id in idlist:
    builder.append('  {{"{0}", {1}::{0}}},'.format(id, csname))
  builder.append("};")
  return "\n".join(builder)

def gen_rev_ecs_map(csname, idlist, gvarName):
  """
  以下のような文字列からenum idのlookupをするmapを生成。
  static const std::map<TokenType, std::string> g_revMap{
    {TokenType::UNKNOWN, "OFFSET_IS_OUTSIDE_OF_SOURCE_SIZE"},
    ...
  };

  ここでcsnameはTokenTypeに、gvarNameはg_revMapに対応する。
  """
  builder = []
  builder.append(f"static const std::map<{csname}, std::string> {gvarName}{{")
  for id in idlist:
    builder.append('  {{{1}::{0}, "{0}"}},'.format(id, csname))
  builder.append("};")
  return "\n".join(builder)


@task
def gen_emap_cpp(c):
  """
  mfg_resource.hppのenum定義から、mfg_resource_gen.cppを生成。
  """
  resIds = collect_enum_ids("../mfg_resource.hpp", "ResId")
  uiResIds = collect_enum_ids("../mfg_resource.hpp", "UIResId")
  ttIds = collect_enum_ids("../../_mfg/mfg_parser.hpp", "TokenType")
  cppname = "../mfg_resource_gen.cpp"
  res_map_def = gen_res_map("ResId", resIds, "g_resMap")
  ui_res_map_def = gen_res_map("UIResId", uiResIds, "g_uiResMap")
  rev_tt_map_def = gen_rev_ecs_map("TokenType", ttIds, "g_revTTMap" );

  content = f"{cpp_header}{res_map_def}\n\n{ui_res_map_def}{cpp_resmap_gen_footer}{resourece_ns_footer}{parser_ns_header}{rev_tt_map_def}{cpp_revres_map_gen_footer}{parser_ns_footer}"
  # print(content)

  with open(cppname, 'w', encoding='utf_8_sig') as fcpp:
    fcpp.write(content)

def update_trans_cpp(hpp, ecsname, cpp, funcName):
  """
  hpp: enum classのあるファイルのパス(例: "../mfg_resource.hpp")
  ecsname: enum classの名前(例: "ResId")
  cpp: コメントを追加するcppのパス(例: "../mfg_resource_trans_str.cpp")
  funcName: コメントを追加する関数名（例: "ResourceStringGen")

  mfg_resource.hppのenumのIDにあって、mfg_resource_trans_str.cppの言語ごと（及び最後のデフォルト言語）のcaseに無いものを、
  以下のようなC++コメントとして追加する
  // case ResId::SOME_ID: return "";
  """  
  ids = collect_enum_ids(hpp, ecsname)
  res = update_trans_str_case(cpp, ecsname, funcName, ids)
  with open(cpp, 'w', encoding='utf_8_sig') as fcpp:
    fcpp.write(res)

@task
def update_trans_str_cpp(c):
  """
  mfg_resource.hppのenumのIDにあって、mfg_resource_trans_str.cppの言語ごと（及び最後のデフォルト言語）のcaseに無いものを、
  以下のようなC++コメントとして追加する
  // case ResId::SOME_ID: return "";
  """  
  update_trans_cpp("../mfg_resource.hpp", "ResId", "../mfg_resource_trans_str.cpp", "ResourceStringGen")

@task
def update_ui_trans_str_cpp(c):
  """
  mfg_resource.hppのenumのIDにあって、mfg_resource_ui_trans_str.cppの言語ごと（及び最後のデフォルト言語）のcaseに無いものを、
  以下のようなC++コメントとして追加する
  // case ResId::SOME_ID: return "";
  """  
  update_trans_cpp("../mfg_resource.hpp", "UIResId", "../mfg_resource_ui_trans_str.cpp", "UIResourceStringGen")


@task
def update_all(c):
  """
  mfg_resource.hppを元に更新すべき事を全部行う。
  現時点ではgen-emap-cppしてupdate-trans-cppする。
  """
  gen_emap_cpp(c)
  update_trans_str_cpp(c)
  update_ui_trans_str_cpp(c)
