/* -*- coding: utf-8 -*- マルチバイト */

// Copyright 2026 PGN Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#if defined(_MSC_VER)
  #pragma execution_character_set("utf-8")
#endif

#include <trans.h>
#include "trans_str_menu_file.h"

///////////////////////////////////////////////////////////////////////////
// - ファイルメニューで使用される文字列
// - A string used in the file menu.
///////////////////////////////////////////////////////////////////////////
QString Trans_StrMenuFile( int idx )
{
  CTranslationManager* man = &Trans();

  //////////////////////////////////
  //////////////////////////////////
  if (man->TranslateJapanese())
  {
    if (idx == 0) return QObject::tr("ファイル(&F)");
    if (idx == 1) return QObject::tr("新規作成(&N)...");
    if (idx == 2) return QObject::tr("クリップボードから新規作成(&V)");
    if (idx == 3) return QObject::tr("開く(&O)...");
    if (idx == 4) return QObject::tr("最近使ったファイル(&R)");
    if (idx == 5) return QObject::tr("保存(&S)");
    if (idx == 6) return QObject::tr("名前をつけて保存(&A)...");
    if (idx == 7) return QObject::tr("ラスタライズ(&Z)...");
    if (idx == 8) return QObject::tr("環境設定(&K)...");
    if (idx == 9) return QObject::tr("閉じる(&C)");
    if (idx == 10) return QObject::tr("ショートカット設定(&H)...");
    if (idx == 11) return QObject::tr("印刷(&P)...");
    if (idx == 12) return QObject::tr("レイヤーを連番出力...");
    if (idx == 13) return QObject::tr("書き出し...");
    if (idx == 14) return QObject::tr("画像をレイヤーとして開く...");
    if (idx == 15) return QObject::tr("書き出し (CMYK形式 PSD)...");
    if (idx == 16) return QObject::tr("ブラシ環境設定(&B)...");
    if (idx == 17) return QObject::tr("新規レイヤーとして開く(&L)...");
    if (idx == 18) return QObject::tr("名前をつけてエクスポート(日時を指定)(&D)...");
    if (idx == 19) return QObject::tr("アニメーション書き出し (APNG)...");
    if (idx == 20) return QObject::tr("アニメーション書き出し (アニメーションGIF)...");
    if (idx == 21) return QObject::tr("最近使ったフォルダ(&F)");
    if (idx == 22) return QObject::tr("自動バックアップフォルダを開く...");
    if (idx == 23) return QObject::tr("書き出し (ICO)...");
    if (idx == 24) return QObject::tr("アニメーション書き出し (MP4)...");
    if (idx == 25) return QObject::tr("書き出し (Base64/PNG)...");
    if (idx == 26) return QObject::tr("筆圧APIの選択...");
    if (idx == 27) return QObject::tr("タイムラプス");
    if (idx == 28) return QObject::tr("録画の開始...");
    if (idx == 29) return QObject::tr("録画の終了...");
    if (idx == 30) return QObject::tr("テンプレートから新規作成(&T)...");
    if (idx == 31) return QObject::tr("常にタイムラプスを録画する...");
    if (idx == 32) return QObject::tr("タイムラプス保存フォルダを開く...");
    if (idx == 33) return QObject::tr("アニメーション書き出し");
    if (idx == 34) return QObject::tr("書き出し...");
  }

  //////////////////////////////////
  //////////////////////////////////
  if (man->TranslateChineseSimp())
  {
    if (idx == 0) return QObject::tr("档案(&F)");
    if (idx == 1) return QObject::tr("新建档案(&N)...");
    if (idx == 2) return QObject::tr("从剪贴板新建(&V)");
    if (idx == 3) return QObject::tr("打开(&O)...");
    if (idx == 4) return QObject::tr("最近使用的档案(&R)");
    if (idx == 5) return QObject::tr("保存(&S)");
    if (idx == 6) return QObject::tr("另存为(&A)...");
    if (idx == 7) return QObject::tr("点阵化(&Z)...");
    if (idx == 8) return QObject::tr("环境设定(&K)...");
    if (idx == 9) return QObject::tr("关闭(&C)");
    if (idx == 10) return QObject::tr("设定快捷键(&H)...");
    if (idx == 11) return QObject::tr("打印(&P)...");
    if (idx == 12) return QObject::tr("按序导出图层(描图纸模式)...");
    if (idx == 13) return QObject::tr("输出..."); // 書き出し...
    if (idx == 14) return QObject::tr("图像以图层形式开启"); // 画像をレイヤーとして開く...
    if (idx == 15) return QObject::tr("输出 (CMYK形式 PSD)..."); // 書き出し (CMYK形式 PSD)...
    if (idx == 16) return QObject::tr("笔刷环境设定 (&B)..."); // ブラシ環境設定(&B)...
    if (idx == 17) return QObject::tr("以新图层方式开启 (&L)..."); // 新規レイヤーとして開く(&L)...
    if (idx == 18) return QObject::tr("命名后输出(指定时间)(&D)..."); // 名前をつけてエクスポート(日時を指定)(&D)...
    if (idx == 19) return QObject::tr("输出动画 (APNG)..."); // アニメーション書き出し (APNG)...
    if (idx == 20) return QObject::tr("输出动画 (GIF)..."); // アニメーション書き出し (アニメーションGIF)...
    if (idx == 21) return QObject::tr("最近使用的资聊夹(&F)"); // 最近使ったフォルダ(&F)
    if (idx == 22) return QObject::tr("开启备档资料夹"); // 自動バックアップフォルダを開く...
    if (idx == 23) return QObject::tr("输出 (ICO)..."); // 書き出し (ICO)...
    if (idx == 24) return QObject::tr("输出动画 (MP4)..."); // アニメーション書き出し (MP4)...
    if (idx == 25) return QObject::tr("输出 (Base64/PNG)..."); // 書き出し (Base64/PNG)...
    if (idx == 26) return QObject::tr("选择笔压API"); // 筆圧APIの選択...
    if (idx == 27) return QObject::tr("缩时摄影"); // タイムラプス
    if (idx == 28) return QObject::tr("开始录影..."); // 録画の開始...
    if (idx == 29) return QObject::tr("结束录影..."); // 録画の終了...
    if (idx == 30) return QObject::tr("从模板新建(&T)..."); // テンプレートから新規作成(&T)...
    if (idx == 31) return QObject::tr("始终录制延时摄影..."); // 常にタイムラプスを録画する...
    if (idx == 32) return QObject::tr("打开延时摄影保存文件夹..."); // タイムラプス保存フォルダを開く...
    if (idx == 33) return QObject::tr("输出动画"); // アニメーション書き出し
    if (idx == 34) return QObject::tr("输出"); // 書き出し
  }

  //////////////////////////////////
  //////////////////////////////////
  if (man->TranslateChineseTrad())
  {
    if (idx == 0) return QObject::tr("檔案(&F)");
    if (idx == 1) return QObject::tr("新建檔案(&N)...");
    if (idx == 2) return QObject::tr("從剪貼簿新建檔案(&V)");
    if (idx == 3) return QObject::tr("開啟(&O)...");
    if (idx == 4) return QObject::tr("最近使用的檔案(&R)");
    if (idx == 5) return QObject::tr("儲存(&S)");
    if (idx == 6) return QObject::tr("另存新檔(&A)...");
    if (idx == 7) return QObject::tr("點陣化(&Z)...");
    if (idx == 8) return QObject::tr("環境設定(&K)...");
    if (idx == 9) return QObject::tr("關閉(&C)");
    if (idx == 10) return QObject::tr("設定快捷鍵(&H)...");
    if (idx == 11) return QObject::tr("列印(&P)...");
    if (idx == 12) return QObject::tr("連續匯出圖層（描圖紙模式）...");
    if (idx == 13) return QObject::tr("輸出..."); // 書き出し...
    if (idx == 14) return QObject::tr("圖像以圖層形式開啟"); // 画像をレイヤーとして開く...
    if (idx == 15) return QObject::tr("輸出 (CMYK形式 PSD)..."); // 書き出し (CMYK形式 PSD)...
    if (idx == 16) return QObject::tr("筆刷環境設定 (&B)..."); // ブラシ環境設定(&B)...
    if (idx == 17) return QObject::tr("以新圖層方式開啟 (&L)..."); // 新規レイヤーとして開く(&L)...
    if (idx == 18) return QObject::tr("命名後輸出(指定時間)(&D)..."); // 名前をつけてエクスポート(日時を指定)(&D)...
    if (idx == 19) return QObject::tr("輸出動畫 (APNG)..."); // アニメーション書き出し (APNG)...
    if (idx == 20) return QObject::tr("輸出動畫 (GIF)..."); // アニメーション書き出し (アニメーションGIF)...
    if (idx == 21) return QObject::tr("最近使用的資聊夾(&F)"); // アニメーション書き出し (アニメーションGIF)...
    if (idx == 22) return QObject::tr("開啟備檔資料夾"); // 自動バックアップフォルダを開く...
    if (idx == 23) return QObject::tr("輸出 (ICO)..."); // 書き出し (ICO)...
    if (idx == 24) return QObject::tr("輸出動畫 (MP4)..."); // アニメーション書き出し (MP4)...
    if (idx == 25) return QObject::tr("輸出 (Base64/PNG)..."); // 書き出し (Base64/PNG)...
    if (idx == 26) return QObject::tr("選擇筆壓API"); // 筆圧APIの選択...
    if (idx == 27) return QObject::tr("縮時攝影"); // タイムラプス
    if (idx == 28) return QObject::tr("開始錄影..."); // 録画の開始...
    if (idx == 29) return QObject::tr("結束錄影..."); // 録画の終了...
    if (idx == 30) return QObject::tr("從模板新建(&T)..."); // テンプレートから新規作成(&T)...
    if (idx == 31) return QObject::tr("始終錄製縮時攝影..."); // 常にタイムラプスを録画する...
    if (idx == 32) return QObject::tr("開啟縮時攝影的儲存資料夾..."); // タイムラプス保存フォルダを開く...
    if (idx == 33) return QObject::tr("輸出動畫"); // アニメーション書き出し
    if (idx == 34) return QObject::tr("輸出"); // 書き出し
  }

  //////////////////////////////////
  //////////////////////////////////
  if (man->TranslateKorean())
  {
    if (idx == 0) return QObject::tr("파일(&F)");
    if (idx == 1) return QObject::tr("신규 작성(&N)...");
    if (idx == 2) return QObject::tr("클립 보드에서 신규 작성(&V)");
    if (idx == 3) return QObject::tr("열기(&O)...");
    if (idx == 4) return QObject::tr("최근 사용한 파일(&R)");
    if (idx == 5) return QObject::tr("저장(&S)");
    if (idx == 6) return QObject::tr("다른 이름으로 저장(&A)...");
    if (idx == 7) return QObject::tr("래스터화(&Z)...");
    if (idx == 8) return QObject::tr("환경설정(&K)...");
    if (idx == 9) return QObject::tr("닫기(&C)");
    if (idx == 10) return QObject::tr("단축키 설정(&H)...");
    if (idx == 11) return QObject::tr("인쇄(&P)...");
    if (idx == 12) return QObject::tr("레이어 일련번호 생성하여 내보내기");
    if (idx == 13) return QObject::tr("내보내기..."); // 書き出し...
    if (idx == 14) return QObject::tr("이미지를 레이어로 열기..."); // 画像をレイヤーとして開く...
    if (idx == 15) return QObject::tr("내보내기 (CMYK 형식 PSD)..."); // 書き出し (CMYK形式 PSD)...
    if (idx == 16) return QObject::tr("브러시 환경설정(&B)..."); // ブラシ環境設定(&B)...
    if (idx == 17) return QObject::tr("신규 레이어로 열기(&L)..."); // 新規レイヤーとして開く(&L)...
    if (idx == 18) return QObject::tr("이름을 지정하여 내보내기(날짜 및 시간 지정)(&D)..."); // 名前をつけてエクスポート(日時を指定)(&D)...
    if (idx == 19) return QObject::tr("애니메이션 내보내기 (APNG)..."); // アニメーション書き出し (APNG)...
    if (idx == 20) return QObject::tr("애니메이션 내보내기 (애니메이션 GIF)..."); // アニメーション書き出し (アニメーションGIF)...
    if (idx == 21) return QObject::tr("최근 사용한 폴더(&F)"); // 最近使ったフォルダ(&F)
    if (idx == 22) return QObject::tr("자동 백업 폴더 열기..."); // 自動バックアップフォルダを開く...
    if (idx == 23) return QObject::tr("내보내기 (ICO)..."); // 書き出し (ICO)...
    if (idx == 24) return QObject::tr("애니메이션 내보내기 (MP4)..."); // アニメーション書き出し (MP4)...
    if (idx == 25) return QObject::tr("내보내기 (Base64/PNG)..."); // 書き出し (Base64/PNG)...
    if (idx == 26) return QObject::tr("필압 API 선택..."); // 筆圧APIの選択...
    if (idx == 27) return QObject::tr("타임랩스"); // タイムラプス
    if (idx == 28) return QObject::tr("녹화 시작..."); // 録画の開始...
    if (idx == 29) return QObject::tr("녹화 종료..."); // 録画の終了...
    if (idx == 30) return QObject::tr("템플릿에서 새로 만들기(&T)..."); // テンプレートから新規作成(&T)...
    if (idx == 31) return QObject::tr("항상 타임랩스를 녹화..."); // 常にタイムラプスを録画する...
    if (idx == 32) return QObject::tr("타임랩스 저장 폴더 열기..."); // タイムラプス保存フォルダを開く...
    if (idx == 33) return QObject::tr("애니메이션 내보내기"); // アニメーション書き出し
    if (idx == 34) return QObject::tr("내보내기"); // 書き出し
  }

  //////////////////////////////////
  //////////////////////////////////
  if (man->TranslatePortugues())
  {
    if (idx == 0) return QObject::tr("Arquivo(&F)");
    if (idx == 1) return QObject::tr("Novo(&N)...");
    if (idx == 2) return QObject::tr("Novo via Área de Transferência(&V)");
    if (idx == 3) return QObject::tr("Abrir(&O)...");
    if (idx == 4) return QObject::tr("Abrir Arquivo Recente(&R)");
    if (idx == 5) return QObject::tr("Salvar(&S)");
    if (idx == 6) return QObject::tr("Salvar Como(&A)...");
    if (idx == 7) return QObject::tr("Rasterizar(&Z)...");
    if (idx == 8) return QObject::tr("Configuração do Ambiente(&K)...");
    if (idx == 9) return QObject::tr("Fechar(&C)");
    if (idx == 10) return QObject::tr("Configuração de Atalhos(&H)...");
    if (idx == 11) return QObject::tr("Imprimir(&P)..."); // 印刷(&P)...
    if (idx == 12) return QObject::tr("Exportar Camadas em Sequência..."); // レイヤーを連番出力...
    if (idx == 13) return QObject::tr("Exportar..."); // 書き出し...
    if (idx == 14) return QObject::tr("Abrir Imagem como Camada..."); // 画像をレイヤーとして開く...
    if (idx == 15) return QObject::tr("Exportar (Formato CMYK PSD)..."); // 書き出し (CMYK形式 PSD)...
    if (idx == 16) return QObject::tr("Configurações do Pincel (&B)..."); // ブラシ環境設定(&B)...
    if (idx == 17) return QObject::tr("Abrir como Nova Camada (&L)..."); // 新規レイヤーとして開く(&L)...
    if (idx == 18) return QObject::tr("Exportar com Nome Específico (com Data e Hora) (&D)..."); // 名前をつけてエクスポート(日時を指定)(&D)...
    if (idx == 19) return QObject::tr("Exportar Animação (APNG)...."); // アニメーション書き出し (APNG)...
    if (idx == 20) return QObject::tr("Exportar Animação (GIF Animado)..."); // アニメーション書き出し (アニメーションGIF)...
    if (idx == 21) return QObject::tr("Pastas Recentes (&F)"); // 最近使ったフォルダ(&F)
    if (idx == 22) return QObject::tr("Abrir Pasta de Backup Automático..."); // 自動バックアップフォルダを開く...
    if (idx == 23) return QObject::tr("Exportar (ICO)..."); // 書き出し (ICO)...
    if (idx == 24) return QObject::tr("Exportar Animação (MP4)..."); // アニメーション書き出し (MP4)...
    if (idx == 25) return QObject::tr("Exportar (Base64/PNG)..."); // 書き出し (Base64/PNG)...
    if (idx == 26) return QObject::tr("Selecionar API de Pressão do Pincel..."); // 筆圧APIの選択...
    if (idx == 27) return QObject::tr("Timelapse"); // タイムラプス
    if (idx == 28) return QObject::tr("Iniciar Gravação..."); // 録画の開始...
    if (idx == 29) return QObject::tr("Parar Gravação..."); // 録画の終了...
    if (idx == 30) return QObject::tr("Criar novo a partir de modelo(&T)..."); // テンプレートから新規作成(&T)...
    if (idx == 31) return QObject::tr("Gravar timelapse sempre..."); // 常にタイムラプスを録画する...
    if (idx == 32) return QObject::tr("Abrir a pasta de salvamento do timelapse..."); // タイムラプス保存フォルダを開く...
    if (idx == 33) return QObject::tr("Exportar Animação"); // アニメーション書き出し
    if (idx == 34) return QObject::tr("Exportar"); // 書き出し
  }

  //////////////////////////////////
  //////////////////////////////////
  if (man->TranslateSpanish())
  {
    if (idx == 0) return QObject::tr("Archivo(&F)");
    if (idx == 1) return QObject::tr("Nuevo(&N)...");
    if (idx == 2) return QObject::tr("Nuevo desde el portapapeles(&V)");
    if (idx == 3) return QObject::tr("Abrir(&O)...");
    if (idx == 4) return QObject::tr("Abrir archivo reciente(&R)");
    if (idx == 5) return QObject::tr("Guardar(&S)");
    if (idx == 6) return QObject::tr("Guardar como(&A)...");
    if (idx == 7) return QObject::tr("Rasterizar(&Z)...");
    if (idx == 8) return QObject::tr("Preferencias(&K)...");
    if (idx == 9) return QObject::tr("Cerrar(&C)");
    if (idx == 10) return QObject::tr("Configurar acceso directo(&H)...");
    if (idx == 11) return QObject::tr("Impresión(&P)..."); // 印刷(&P)...
    if (idx == 12) return QObject::tr("Exportar capas secuencialmente..."); // レイヤーを連番出力...
    if (idx == 13) return QObject::tr("Exportar..."); // 書き出し...
    if (idx == 14) return QObject::tr("Abrir imagen como capa"); // 画像をレイヤーとして開く...
    if (idx == 15) return QObject::tr("Exportar (formato CMYK PSD)..."); // 書き出し (CMYK形式 PSD)...
    if (idx == 16) return QObject::tr("Preferencias de pincel(&B)..."); // ブラシ環境設定(&B)...
    if (idx == 17) return QObject::tr("Abrir como nueva capa(&L)..."); // 新規レイヤーとして開く(&L)...
    if (idx == 18) return QObject::tr("Exportar como (especificar fecha y hora)(&D)..."); // 名前をつけてエクスポート(日時を指定)(&D)...
    if (idx == 19) return QObject::tr("Exportar animación (APNG)..."); // アニメーション書き出し (APNG)...
    if (idx == 20) return QObject::tr("Exportar animación (GIF animado)..."); // アニメーション書き出し (アニメーションGIF)...
    if (idx == 21) return QObject::tr("Carpetas usadas recientemente(&F)"); // 最近使ったフォルダ(&F)
    if (idx == 22) return QObject::tr("Abrir carpeta de copia de seguridad automática..."); // 自動バックアップフォルダを開く...
    if (idx == 23) return QObject::tr("Exportar (ICO)..."); // 書き出し (ICO)...
    if (idx == 24) return QObject::tr("Exportar animación (MP4)..."); // アニメーション書き出し (MP4)...
    if (idx == 25) return QObject::tr("Exportar (Base64/PNG)..."); // 書き出し (Base64/PNG)...
    if (idx == 26) return QObject::tr("Selección de API de presión de lápiz..."); // 筆圧APIの選択...
    if (idx == 27) return QObject::tr("Lapso de tiempo"); // タイムラプス
    if (idx == 28) return QObject::tr("Iniciar grabación..."); // 録画の開始...
    if (idx == 29) return QObject::tr("Fin de la grabación..."); // 録画の終了...
    if (idx == 30) return QObject::tr("Crear nuevo desde plantilla(&T)..."); // テンプレートから新規作成(&T)...
    if (idx == 31) return QObject::tr("Grabar timelapse siempre..."); // 常にタイムラプスを録画する...
    if (idx == 32) return QObject::tr("Abrir la carpeta de guardado del timelapse..."); // タイムラプス保存フォルダを開く...
    if (idx == 33) return QObject::tr("Exportar animación"); // アニメーション書き出し
    if (idx == 34) return QObject::tr("Exportar"); // 書き出し
  }

  //////////////////////////////////
  //////////////////////////////////
  if (man->TranslateGerman())
  {
    if (idx == 0) return QObject::tr("Datei(&F)");
    if (idx == 1) return QObject::tr("Neu(&N)...");
    if (idx == 2) return QObject::tr("Neues über Zwischenablage(&V)");
    if (idx == 3) return QObject::tr("Öffnen(&O)...");
    if (idx == 4) return QObject::tr("Kürzliche Datei öffnen(&R)");
    if (idx == 5) return QObject::tr("Speichern(&S)");
    if (idx == 6) return QObject::tr("Speichern als(&A)...");
    if (idx == 7) return QObject::tr("Rastern(&Z)...");
    if (idx == 8) return QObject::tr("Umgebungseinstellung(&K)...");
    if (idx == 9) return QObject::tr("Schließen(&C)");
    if (idx == 10) return QObject::tr("Einstellung für Abkürzung(&H)...");
    if (idx == 11) return QObject::tr("Drucken(&P)..."); // 印刷(&P)...
    if (idx == 12) return QObject::tr("Ebenen exportieren..."); // レイヤーを連番出力...
    if (idx == 13) return QObject::tr("Exportieren..."); // 書き出し...
    if (idx == 14) return QObject::tr("Das Bild als Ebene öffnen"); // 画像をレイヤーとして開く...
    if (idx == 15) return QObject::tr("Exportieren (CMYK-Format PSD)..."); // 書き出し (CMYK形式 PSD)...
    if (idx == 16) return QObject::tr("Pinselumgebung Einstellungen(&B)..."); // ブラシ環境設定(&B)...
    if (idx == 17) return QObject::tr("Als neue Ebene öffnen(&L)..."); // 新規レイヤーとして開く(&L)...
    if (idx == 18) return QObject::tr("Exportieren als (Datum angeben)(&D)..."); // 名前をつけてエクスポート(日時を指定)(&D)...
    if (idx == 19) return QObject::tr("Animation exportieren (APNG)..."); // アニメーション書き出し (APNG)...
    if (idx == 20) return QObject::tr("Animation exportieren (Animiertes GIF)..."); // アニメーション書き出し (アニメーションGIF)...
    if (idx == 21) return QObject::tr("Letzten Ordner öffnen(&F)"); // 最近使ったフォルダ(&F)
    if (idx == 22) return QObject::tr("Auto-Backup-Ordner öffnen..."); // 自動バックアップフォルダを開く...
    if (idx == 23) return QObject::tr("Exportieren (ICO)..."); // 書き出し (ICO)...
    if (idx == 24) return QObject::tr("Animation exportieren (MP4)..."); // アニメーション書き出し (MP4)...
    if (idx == 25) return QObject::tr("Exportieren (Base64/PNG)..."); // 書き出し (Base64/PNG)...
    if (idx == 26) return QObject::tr("Stiftdruck-API auswählen..."); // 筆圧APIの選択...
    if (idx == 27) return QObject::tr("Zeitraffer"); // タイムラプス
    if (idx == 28) return QObject::tr("Aufnahme starten..."); // 録画の開始...
    if (idx == 29) return QObject::tr("Aufnahme beenden..."); // 録画の終了...
    if (idx == 30) return QObject::tr("Neu erstellen aus Vorlage(&T)..."); // テンプレートから新規作成(&T)...
    if (idx == 31) return QObject::tr("Timelapse immer aufzeichnen..."); // 常にタイムラプスを録画する...
    if (idx == 32) return QObject::tr("Ordner für Timelapse-Speicherung öffnen..."); // タイムラプス保存フォルダを開く...
    if (idx == 33) return QObject::tr("Animation exportieren"); // アニメーション書き出し
    if (idx == 34) return QObject::tr("Exportieren"); // 書き出し
  }

  //////////////////////////////////
  //////////////////////////////////
  if (man->TranslateFrench())
  {
    if (idx == 0) return QObject::tr("Fichier(&F)");
    if (idx == 1) return QObject::tr("Nouveau(&N)...");
    if (idx == 2) return QObject::tr("Nouveau via le presse-papiers(&V)");
    if (idx == 3) return QObject::tr("Ouvrir(&O)...");
    if (idx == 4) return QObject::tr("Ouvrir un fichier récent(&R)");
    if (idx == 5) return QObject::tr("Enregistrer(&S)");
    if (idx == 6) return QObject::tr("Enregistrer sous(&A)...");
    if (idx == 7) return QObject::tr("Pixellisation (&Z)...");
    if (idx == 8) return QObject::tr("Paramètre d'environnement(&K)...");
    if (idx == 9) return QObject::tr("Fermer(&C)");
    if (idx == 10) return QObject::tr("Paramètre de raccourci(&H)...");
    if (idx == 11) return QObject::tr("Imprimer(&P)..."); // 印刷(&P)...
    if (idx == 12) return QObject::tr("Exporter les calques..."); // レイヤーを連番出力...
    if (idx == 13) return QObject::tr("Exporter..."); // 書き出し...
    if (idx == 14) return QObject::tr("Ouvrir l'image en tant que calque"); // 画像をレイヤーとして開く...
    if (idx == 15) return QObject::tr("Exporter (format PSD CMJN)..."); // 書き出し (CMYK形式 PSD)...
    if (idx == 16) return QObject::tr("Paramètres de l'environnement du pinceau(&B)..."); // ブラシ環境設定(&B)...
    if (idx == 17) return QObject::tr("Ouvrir en tant que nouveau calque(&L)..."); // 新規レイヤーとして開く(&L)...
    if (idx == 18) return QObject::tr("Exporter sous (spécifier la date)(&D)..."); // 名前をつけてエクスポート(日時を指定)(&D)...
    if (idx == 19) return QObject::tr("Exporter l'animation (APNG)..."); // アニメーション書き出し (APNG)...
    if (idx == 20) return QObject::tr("Exporter l'animation (GIF animé)..."); // アニメーション書き出し (アニメーションGIF)...
    if (idx == 21) return QObject::tr("Ouvrir le dossier récent(&F)"); // 最近使ったフォルダ(&F)
    if (idx == 22) return QObject::tr("Ouvrir le dossier de sauvegarde automatique..."); // 自動バックアップフォルダを開く...
    if (idx == 23) return QObject::tr("Exporter (ICO)..."); // 書き出し (ICO)...
    if (idx == 24) return QObject::tr("Exporter l'animation (MP4)..."); // アニメーション書き出し (MP4)...
    if (idx == 25) return QObject::tr("Exporter (Base64/PNG)..."); // 書き出し (Base64/PNG)...
    if (idx == 26) return QObject::tr("Sélectionner l'API de pression du stylet..."); // 筆圧APIの選択...
    if (idx == 27) return QObject::tr("Accéléré"); // タイムラプス
    if (idx == 28) return QObject::tr("Démarrer l'enregistrement..."); // 録画の開始...
    if (idx == 29) return QObject::tr("Fin de l'enregistrement..."); // 録画の終了...
    if (idx == 30) return QObject::tr("Créer un nouveau à partir d’un modèle (&T)..."); // テンプレートから新規作成(&T)...
    if (idx == 31) return QObject::tr("Toujours enregistrer un timelapse..."); // 常にタイムラプスを録画する...
    if (idx == 32) return QObject::tr("Ouvrir le dossier de sauvegarde du timelapse..."); // タイムラプス保存フォルダを開く...
    if (idx == 33) return QObject::tr("Exporter l'animation"); // アニメーション書き出し
    if (idx == 34) return QObject::tr("Exporter"); // 書き出し
  }

  //////////////////////////////////
  //////////////////////////////////
  if (man->TranslateRussian())
  {
    if (idx == 0) return QObject::tr("Файл(&F)");
    if (idx == 1) return QObject::tr("Новый(&N)...");
    if (idx == 2) return QObject::tr("Новый через буфер обмена(&V)");
    if (idx == 3) return QObject::tr("Открыть(&O)...");
    if (idx == 4) return QObject::tr("Открыть последний файл(&R)");
    if (idx == 5) return QObject::tr("Сохранить(&S)");
    if (idx == 6) return QObject::tr("Сохранить как(&A)...");
    if (idx == 7) return QObject::tr("Растрировать(&Z)...");
    if (idx == 8) return QObject::tr("Настройки среды(&K)...");
    if (idx == 9) return QObject::tr("Закрыть(&C)");
    if (idx == 10) return QObject::tr("Настройки горячих клавиш(&H)...");
    if (idx == 11) return QObject::tr("Печать(&P)..."); // 印刷(&P)...
    if (idx == 12) return QObject::tr("Экспорт слои..."); // レイヤーを連番出力...
    if (idx == 13) return QObject::tr("Экспорт..."); // 書き出し...
    if (idx == 14) return QObject::tr("Открыть изображение как слой"); // 画像をレイヤーとして開く...
    if (idx == 15) return QObject::tr("Экспорт (CMYK в формате PSD)..."); // 書き出し (CMYK形式 PSD)...
    if (idx == 16) return QObject::tr("Настройки среды кисти(&B)..."); // ブラシ環境設定(&B)...
    if (idx == 17) return QObject::tr("Открыть как слой(&L)..."); // 新規レイヤーとして開く(&L)...
    if (idx == 18) return QObject::tr("Экспорт как (Указать дату)(&D)..."); // 名前をつけてエクスポート(日時を指定)(&D)...
    if (idx == 19) return QObject::tr("Экспорт анимации (APNG)..."); // アニメーション書き出し (APNG)...
    if (idx == 20) return QObject::tr("Экспорт анимации (Animated GIF)..."); // アニメーション書き出し (アニメーションGIF)...
    if (idx == 21) return QObject::tr("Открыть последнюю папку(&F)"); // 最近使ったフォルダ(&F)
    if (idx == 22) return QObject::tr("Открыть папку авторезервного копирования..."); // 自動バックアップフォルダを開く...
    if (idx == 23) return QObject::tr("Экспорт (ICO)..."); // 書き出し (ICO)...
    if (idx == 24) return QObject::tr("Экспорт анимации (MP4)..."); // アニメーション書き出し (MP4)...
    if (idx == 25) return QObject::tr("Экспорт (Base64/PNG)..."); // 書き出し (Base64/PNG)...
    if (idx == 26) return QObject::tr("Выбрать API давления пера..."); // 筆圧APIの選択...
    if (idx == 27) return QObject::tr("Таймлапс"); // タイムラプス
    if (idx == 28) return QObject::tr("Начать запись..."); // 録画の開始...
    if (idx == 29) return QObject::tr("Завершить запись..."); // 録画の終了...
    if (idx == 30) return QObject::tr("Создать новый из шаблона(&T)..."); // テンプレートから新規作成(&T)...
    //if (idx == 31) return QObject::tr("Always Record Timelapse..."); // 常にタイムラプスを録画する...
    //if (idx == 32) return QObject::tr("Open Timelapse Save Folder..."); // タイムラプス保存フォルダを開く...
    if (idx == 33) return QObject::tr("Экспорт анимации"); // アニメーション書き出し
    if (idx == 34) return QObject::tr("Экспорт"); // 書き出し
  }

  //////////////////////////////////
  //////////////////////////////////
  if (man->TranslateHindi())
  {
  }

  if (man->TranslateBengali())
  {
  }

  if (man->TranslatePolish())
  {
  }

  ///////////////////////////////////////////////////
  ///////////////////////////////////////////////////
  // 英語は mainwindow.ui が使われるので、下の翻訳は使われない
  ///////////////////////////////////////////////////
  ///////////////////////////////////////////////////
  if (idx == 0) return QObject::tr("File(&F)");
  if (idx == 1) return QObject::tr("New(&N)...");
  if (idx == 2) return QObject::tr("New via Clipboard(&V)");
  if (idx == 3) return QObject::tr("Open(&O)...");
  if (idx == 4) return QObject::tr("Open Recent File(&R)");
  if (idx == 5) return QObject::tr("Save(&S)");
  if (idx == 6) return QObject::tr("Save As(&A)...");
  if (idx == 7) return QObject::tr("Rasterize(&Z)...");
  if (idx == 8) return QObject::tr("Environment Settings(&K)...");
  if (idx == 9) return QObject::tr("Close(&C)");
  if (idx == 10) return QObject::tr("Shortcut Settings(&H)...");
  if (idx == 11) return QObject::tr("Print(&P)...");
  if (idx == 12) return QObject::tr("Export Layers...");
  if (idx == 13) return QObject::tr("Export...");
  if (idx == 14) return QObject::tr("Open the Image as a Layer");
  if (idx == 15) return QObject::tr("Export (CMYK format PSD)...");
  if (idx == 16) return QObject::tr("Brush Environment Settings(&B)...");
  if (idx == 17) return QObject::tr("Open As a New Layer(&L)...");
  if (idx == 18) return QObject::tr("Export As (Specify Date)(&D)...");
  if (idx == 19) return QObject::tr("Export　Animation (APNG)...");
  if (idx == 20) return QObject::tr("Export Animation (Animated GIF)...");
  if (idx == 21) return QObject::tr("Open Recent Folder(&F)");
  if (idx == 22) return QObject::tr("Open the Auto Backup Folder...");
  if (idx == 23) return QObject::tr("Export (ICO)...");
  if (idx == 24) return QObject::tr("Export Animation (MP4)...");
  if (idx == 25) return QObject::tr("Export (Base64/PNG)...");
  if (idx == 26) return QObject::tr("Select Pen Pressure API...");
  if (idx == 27) return QObject::tr("Time-lapse");
  if (idx == 28) return QObject::tr("Start Recording...");
  if (idx == 29) return QObject::tr("End Recording...");
  if (idx == 30) return QObject::tr("Create New from Template(&T)..."); // テンプレートから新規作成(&T)...
  if (idx == 31) return QObject::tr("Always Record Timelapse..."); // 常にタイムラプスを録画する...
  if (idx == 32) return QObject::tr("Open Timelapse Save Folder..."); // タイムラプス保存フォルダを開く...
  if (idx == 33) return QObject::tr("Export　Animation"); // アニメーション書き出し
  if (idx == 34) return QObject::tr("Export"); // 書き出し

  return "";
}
